name: Write Quote of the Day into file. 

on: 
  workflow_dispatch: # manual trigger
 
jobs:
  build: 
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macOS-latest]
        version: [14, 16, 18]
        exclude:
          - platform: windows-latest

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Use Node Js ${{ matrix.version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.version }}
          
#      - name: Initialize Package.json
#        run: npm init --yes
        
      - name: Install Packages
        run: npm install
        
      - name: Provide Permissions to script file
        run: chmod +x ./test.sh 
        
      - name: Running on ${{ matrix.platform }} with Node Js ${{ matrix.version }}
        run: bash ./test.sh ${{ matrix.platform }} ${{ matrix.version }} ${{GITHUB.SHA}}
        
      - name: Git Commit and Push
        run: |
          git config --global user.email "Cschau0701vip@gmail.com"
          git config --global user.name "Cschau0701vip"
          git add -A
          git commit -m "Added Quote of the Day from GitHub Actions using matrix strategy!"
          git pull -ff-only
          git push
  
      
