name: Write Quote of the Day into file. 

on: 
  workflow_dispatch: # manual trigger
 
jobs:
  build: 
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macOS-latest]
        version: [14, 16, 18]
        
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Use Node Js ${{ matrix.version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.version }}
          
      - name: Initialize Package.json
        run: npm init --yes
        
      - name: Install Packages
        run: npm install
        
      - name: Running on ${{ matrix.platform }} with Node Js ${{ matrix.version }}
        run: npm test
